/**
 * Avatar URL helpers. URL-only — `resolveAvatarSrc` and friends return
 * paths to pre-rasterized PNG thumbnails served from `public/avatars/`,
 * not inline SVG. Consumers that need the URL surface (SiteHeader, the
 * mentor showcase, profile pages, etc.) should import from here.
 *
 * SVG rendering (the inline avatar generator, used by the paused
 * layered-avatar pipeline) lives in `./svg.ts` and is imported only by
 * code that actually rasterises avatars at runtime. Splitting the two
 * keeps the 20 MB `./parts` source library out of the main bundle: it
 * only loads when someone reaches a route that uses SVG rendering.
 *
 * Before this split, SiteHeader's `import { resolveAvatarSrc }` pulled
 * `PORTRAITS` (via the old `PORTRAIT_SLOT_COUNT = PORTRAITS.length`
 * derivation) into the eagerly-loaded chunk, dragging mobile FCP to
 * 8 s+ on West African mobile networks.
 */

/**
 * Number of portrait slots in the library. Stable: matches the prompt
 * order in `tools/avatars/prompts.ts`. Hardcoded here so this module
 * can compile without importing `./parts` (which contains 20 MB of
 * inlined SVG data). Update when the portrait library grows.
 */
export const PORTRAIT_SLOT_COUNT = 10;

/**
 * Convenience helper — given a user-ish object (anything with a uid
 * and/or email), return a stable seed string. UID is preferred since
 * it doesn't change if the user updates their email.
 */
export function avatarSeedFor(user: { uid?: string; email?: string | null }): string {
  return user.uid ?? user.email ?? 'staija-default';
}

/**
 * URL of the static-rasterized thumbnail for a given slot. Output
 * is `/avatars/portrait-<slot>.png`, served from `public/avatars/`
 * by Vite (dev) and Vercel's static layer (prod). The thumbs are
 * 256×256 PNGs ~50–80 KB each — orders of magnitude lighter than
 * the inlined SVGs in `parts.ts`.
 *
 * Generated by `npm run avatars:thumbs`.
 */
export function avatarThumbForSlot(slot: number): string {
  if (slot < 0 || slot >= PORTRAIT_SLOT_COUNT) {
    throw new Error(
      `avatarThumbForSlot: slot ${slot} is out of range (0–${PORTRAIT_SLOT_COUNT - 1})`,
    );
  }
  return `/avatars/portrait-${slot}.png`;
}

/**
 * The universal default slot — every user without a custom selection
 * lands on this portrait. Picked deliberately rather than hashed from
 * the seed: the brand wants a consistent "you signed up, here's our
 * default scientist" look for new accounts, not 10 random looks.
 *
 * Currently slot 6 = portrait-twa-glasses (per the slot mapping in
 * tools/avatars/prompts.ts).
 */
const DEFAULT_PORTRAIT_SLOT = 6;

/**
 * URL of the universal-default thumbnail. The `seed` parameter is
 * accepted for API symmetry with the other helpers but is currently
 * ignored — every default-state user gets the same portrait.
 */
export function avatarThumbForSeed(_seed: string): string {
  return avatarThumbForSlot(DEFAULT_PORTRAIT_SLOT);
}

/**
 * Pick the right avatar source for a user, honoring the precedence
 *
 *   uploaded photo  >  picked slot  >  seeded default
 *
 * Returns a URL — either the user's uploaded photo URL or one of the
 * static thumbnail URLs. Components render via `<img src>` directly.
 */
export function resolveAvatarSrc(input: {
  photoURL?: string | null;
  avatarSlot?: number | null;
  seed: string;
}): string {
  if (input.photoURL) return input.photoURL;
  if (
    typeof input.avatarSlot === 'number' &&
    input.avatarSlot >= 0 &&
    input.avatarSlot < PORTRAIT_SLOT_COUNT
  ) {
    return avatarThumbForSlot(input.avatarSlot);
  }
  return avatarThumbForSeed(input.seed);
}
