/**
 * Avatar service. Generates SVG/data-URI avatars deterministically from
 * a seed (typically the user's uid or email).
 *
 * Two ways to use:
 *   - `avatarSvg(seed)`           → raw `<svg>...</svg>` string
 *   - `avatarDataUri(seed)`       → `data:image/svg+xml;...` for `<img src>`
 *
 * Avatars are content-addressed by seed: the same seed always returns
 * the same result, so a memoization cache keyed on seed is safe and
 * cheap. Cache lives in module memory; if it ever gets large, the LRU
 * cap below will evict.
 */

import { createAvatar } from '@dicebear/core'
import { staijaStyle } from './style'
import { PORTRAITS } from './parts'

// Module-level cache. Seed → result. The realistic upper bound is
// "number of distinct users you've ever rendered an avatar for" — for
// a single browser session that's small. Cap at 500 to keep the worst
// case bounded if something goes pathological.
const SVG_CACHE = new Map<string, string>()
const DATA_URI_CACHE = new Map<string, string>()
const CACHE_CAP = 500

function cached<V>(map: Map<string, V>, key: string, compute: () => V): V {
  const hit = map.get(key)
  if (hit !== undefined) return hit
  if (map.size >= CACHE_CAP) {
    // Drop the oldest entry. Insertion order is iteration order in JS Maps.
    const oldest = map.keys().next().value
    if (oldest !== undefined) map.delete(oldest)
  }
  const value = compute()
  map.set(key, value)
  return value
}

export function avatarSvg(seed: string): string {
  return cached(SVG_CACHE, seed, () =>
    createAvatar(staijaStyle, { seed }).toString(),
  )
}

export function avatarDataUri(seed: string): string {
  return cached(DATA_URI_CACHE, seed, () =>
    createAvatar(staijaStyle, { seed }).toDataUri(),
  )
}

/**
 * Convenience helper — given a user-ish object (anything with a uid
 * and/or email), return a stable seed string. UID is preferred since
 * it doesn't change if the user updates their email.
 */
export function avatarSeedFor(user: { uid?: string; email?: string | null }): string {
  return user.uid ?? user.email ?? 'staija-default'
}

/**
 * Number of portrait slots in the library. Stable: matches the prompt
 * order in `tools/avatars/prompts.ts`.
 */
export const PORTRAIT_SLOT_COUNT = PORTRAITS.length

/**
 * Render a specific portrait slot wrapped in the same SVG envelope
 * the seeded path produces. Used by the avatar preview route to pin
 * to a known portrait without hunting for a seed that maps to it via
 * Dicebear's PRNG.
 *
 * Slot indices match `tools/avatars/prompts.ts` — e.g. 1 is the
 * afro-medium portrait used as the Phase 1 test slot.
 */
// Slot results are stable (the library is module-frozen) and each
// data URI is several MB. Caching here is essential: without it, the
// AvatarPicker re-encodes 10 large SVGs on every render — enough to
// crash a Chrome tab on modest hardware.
const SLOT_SVG_CACHE = new Map<number, string>()
const SLOT_DATA_URI_CACHE = new Map<number, string>()

export function avatarSvgForSlot(slot: number): string {
  const cached = SLOT_SVG_CACHE.get(slot)
  if (cached !== undefined) return cached
  const portrait = PORTRAITS[slot]
  if (portrait === undefined) {
    throw new Error(
      `avatarSvgForSlot: slot ${slot} is out of range (0–${PORTRAITS.length - 1})`,
    )
  }
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 80" fill="none" shape-rendering="auto">${portrait}</svg>`
  SLOT_SVG_CACHE.set(slot, svg)
  return svg
}

export function avatarDataUriForSlot(slot: number): string {
  const cached = SLOT_DATA_URI_CACHE.get(slot)
  if (cached !== undefined) return cached
  const svg = avatarSvgForSlot(slot)
  const uri = `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`
  SLOT_DATA_URI_CACHE.set(slot, uri)
  return uri
}

/**
 * The universal default slot — every user without a custom selection
 * lands on this portrait. Picked deliberately rather than hashed from
 * the seed: the brand wants a consistent "you signed up, here's our
 * default scientist" look for new accounts, not 10 random looks.
 *
 * Currently slot 6 = portrait-twa-glasses (per the slot mapping in
 * tools/avatars/prompts.ts).
 */
const DEFAULT_PORTRAIT_SLOT = 6

/**
 * URL of the static-rasterized thumbnail for a given slot. Output
 * is `/avatars/portrait-<slot>.png`, served from `public/avatars/`
 * by Vite (dev) and Vercel's static layer (prod). The thumbs are
 * 256×256 PNGs ~50–80 KB each — orders of magnitude lighter than
 * the inlined SVGs in `parts.ts`.
 *
 * Generated by `npm run avatars:thumbs`.
 */
export function avatarThumbForSlot(slot: number): string {
  if (slot < 0 || slot >= PORTRAIT_SLOT_COUNT) {
    throw new Error(
      `avatarThumbForSlot: slot ${slot} is out of range (0–${PORTRAIT_SLOT_COUNT - 1})`,
    )
  }
  return `/avatars/portrait-${slot}.png`
}

/**
 * URL of the universal-default thumbnail. The `seed` parameter is
 * accepted for API symmetry with the other helpers but is currently
 * ignored — every default-state user gets the same portrait.
 */
export function avatarThumbForSeed(_seed: string): string {
  return avatarThumbForSlot(DEFAULT_PORTRAIT_SLOT)
}

/**
 * Pick the right avatar source for a user, honoring the precedence
 *
 *   uploaded photo  >  picked slot  >  seeded default
 *
 * Returns a URL — either the user's uploaded photo URL or one of the
 * static thumbnail URLs. Components render via `<img src>` directly.
 */
export function resolveAvatarSrc(input: {
  photoURL?: string | null
  avatarSlot?: number | null
  seed: string
}): string {
  if (input.photoURL) return input.photoURL
  if (
    typeof input.avatarSlot === 'number' &&
    input.avatarSlot >= 0 &&
    input.avatarSlot < PORTRAIT_SLOT_COUNT
  ) {
    return avatarThumbForSlot(input.avatarSlot)
  }
  return avatarThumbForSeed(input.seed)
}
